import type { ProductoRecomendadoRecord } from "@/lib/inventario/productos-recomendados";
import type { ExcelSheetSpec } from "@/lib/admin/excel-export";

export const inventarioToExcelSheet = (rows: ProductoRecomendadoRecord[]): ExcelSheetSpec => ({
  name: "inventario",
  headers: [
    "id",
    "desarrollo_id",
    "cluster_id",
    "unidad",
    "tipo",
    "estatus",
    "prototipo_id",
    "precio",
    "superficie_terreno_m2",
    "superficie_construccion_m2",
    "entrega",
    "etapa",
    "torre",
    "nivel",
    "orden",
    "visitable",
    "prioridad_comercial",
    "razones_venta",
    "ubicacion_comercial",
    "instruccion_recorrido",
    "nota_acceso",
    "notas",
    "activo",
    "entregado",
    "escriturado",
    "lista_precios",
    "updated_at",
  ],
  rows: rows.map((row) => ({
    id: row.id,
    desarrollo_id: row.desarrollo_id,
    cluster_id: row.cluster_id,
    unidad: row.unidad,
    tipo: row.tipo,
    estatus: row.estatus,
    prototipo_id: row.prototipo_id,
    precio: row.precio,
    superficie_terreno_m2: row.superficie_terreno_m2,
    superficie_construccion_m2: row.superficie_construccion_m2,
    entrega: row.entrega,
    etapa: row.etapa,
    torre: row.torre,
    nivel: row.nivel,
    orden: row.orden,
    visitable: row.visitable,
    prioridad_comercial: row.prioridad_comercial,
    razones_venta: Array.isArray(row.razones_venta) ? row.razones_venta.join(" | ") : "",
    ubicacion_comercial: row.ubicacion_comercial,
    instruccion_recorrido: row.instruccion_recorrido,
    nota_acceso: row.nota_acceso,
    notas: row.notas,
    activo: row.activo,
    entregado: row.entregado,
    escriturado: row.escriturado,
    lista_precios: row.lista_precios,
    updated_at: row.updated_at,
  })),
});
