import type { ProspectoListRow } from "@/lib/admin/prospectos-service";
import type { ExcelSheetSpec } from "@/lib/admin/excel-export";

const str = (value: unknown) => (value == null ? "" : String(value));

export const prospectosToExcelSheet = (rows: ProspectoListRow[]): ExcelSheetSpec => ({
  name: "prospectos",
  headers: [
    "id",
    "desarrollo_id",
    "xperience_id",
    "nombre",
    "email",
    "telefono",
    "etapa",
    "calificacion",
    "nivel_interes",
    "asesor_id",
    "asesor_nombre",
    "promotor_nombre",
    "campana_id",
    "campana_nombre",
    "partner_id",
    "partner_nombre",
    "origen_ciudad",
    "origen_captacion",
    "medio_contacto",
    "medio_publicitario",
    "producto_nombre",
    "asignado_por",
    "motivo_descarte",
    "motivo_descarte_detalle",
    "visita_agendada_on",
    "visita_agendada_hora",
    "visita_realizada_on",
    "proximo_contacto_on",
    "proximo_contacto_nota",
    "perfil_calificacion_lead",
    "perfil_presupuesto_disponible",
    "perfil_intencion_apartar",
    "perfil_decisor_visita",
    "perfil_vio_publicidad_redes",
    "iscore",
    "seller_score",
    "bandera_correo",
    "bandera_llamada",
    "bandera_whatsapp",
    "bandera_crm",
    "es_spam",
    "es_duplicado",
    "activo",
    "notas",
    "created_at",
    "updated_at",
  ],
  rows: rows.map((row) => ({
    id: row.id,
    desarrollo_id: row.desarrollo_id,
    xperience_id: row.xperience_id,
    nombre: row.nombre,
    email: row.email,
    telefono: row.telefono,
    etapa: row.etapa,
    calificacion: row.calificacion,
    nivel_interes: row.nivel_interes,
    asesor_id: row.asesor_id,
    asesor_nombre: row.asesorNombre,
    promotor_nombre: row.promotor_nombre,
    campana_id: row.campana_id,
    campana_nombre: row.campanaNombre,
    partner_id: row.partner_id,
    partner_nombre: row.partnerNombre,
    origen_ciudad: row.origen_ciudad,
    origen_captacion: row.origen_captacion,
    medio_contacto: row.medio_contacto,
    medio_publicitario: row.medio_publicitario,
    producto_nombre: row.producto_nombre,
    asignado_por: row.asignado_por,
    motivo_descarte: row.motivo_descarte,
    motivo_descarte_detalle: row.motivo_descarte_detalle,
    visita_agendada_on: row.visita_agendada_on,
    visita_agendada_hora: row.visita_agendada_hora,
    visita_realizada_on: row.visita_realizada_on,
    proximo_contacto_on: row.proximo_contacto_on,
    proximo_contacto_nota: row.proximo_contacto_nota,
    perfil_calificacion_lead: row.perfil_calificacion_lead,
    perfil_presupuesto_disponible: row.perfil_presupuesto_disponible,
    perfil_intencion_apartar: row.perfil_intencion_apartar,
    perfil_decisor_visita: row.perfil_decisor_visita,
    perfil_vio_publicidad_redes: row.perfil_vio_publicidad_redes,
    iscore: row.iscore,
    seller_score: row.seller_score,
    bandera_correo: row.bandera_correo,
    bandera_llamada: row.bandera_llamada,
    bandera_whatsapp: row.bandera_whatsapp,
    bandera_crm: row.bandera_crm,
    es_spam: row.es_spam,
    es_duplicado: row.es_duplicado,
    activo: row.activo,
    notas: str(row.notas),
    created_at: row.created_at,
    updated_at: row.updated_at,
  })),
});
