// Generated by scripts/build-mision-la-gavia-catalog.mjs — do not edit by hand.

export const MISION_LA_GAVIA_SIMULADOR_CONFIG = {
  "desarrolloId": "mision-la-gavia",
  "excelSource": "Simulador La Gavia 13abr26 (2).xlsx",
  "listaPrecios": "mar26",
  "numUnidades": 105,
  "numListasPrecio": 11,
  "incrementoEntreListas": 0.03,
  "tasaAnual": 0.11,
  "mesesEntregaDefault": 24,
  "inicioVentas": "2026-02-01",
  "inicioConstruccion": "2026-02-01",
  "mesesConstruccionTorre": 18,
  "esquemasPago": [
    {
      "id": "contado",
      "label": "Contado",
      "descuentoPct": 0.172,
      "enganchePct": 0.9,
      "meses": 0,
      "finiquitoPct": 0.1
    },
    {
      "id": "6msi",
      "label": "6MSI",
      "descuentoPct": 0.154,
      "enganchePct": 0.2,
      "meses": 6,
      "finiquitoPct": 0
    },
    {
      "id": "12msi",
      "label": "12MSI",
      "descuentoPct": 0.135,
      "enganchePct": 0.2,
      "meses": 12,
      "finiquitoPct": 0
    },
    {
      "id": "30-70",
      "label": "30-70",
      "descuentoPct": 0.10099999999999999,
      "enganchePct": 0.3,
      "meses": "varia",
      "finiquitoPct": 0.7
    },
    {
      "id": "15-85",
      "label": "15-85",
      "descuentoPct": 0.086,
      "enganchePct": 0.15,
      "meses": "varia",
      "finiquitoPct": 0.85
    }
  ],
  "descuentosLista": {
    "contado": 0.172,
    "msi303040": 0.07744699804564759,
    "plazo3070": 0.04958043517148136,
    "plazo1585": 0.02334767127965587
  },
  "areasExternas": [
    {
      "minM2": 0,
      "maxM2": 10,
      "factor": 1
    },
    {
      "minM2": 10,
      "maxM2": 20,
      "factor": 0.9
    },
    {
      "minM2": 20,
      "maxM2": 30,
      "factor": 0.8
    },
    {
      "minM2": 30,
      "maxM2": 40,
      "factor": 0.7
    },
    {
      "minM2": 40,
      "maxM2": 50,
      "factor": 0.6
    },
    {
      "minM2": 50,
      "maxM2": 60,
      "factor": 0.5
    },
    {
      "minM2": 60,
      "maxM2": 70,
      "factor": 0.4
    },
    {
      "minM2": 70,
      "maxM2": 80,
      "factor": 0.4
    },
    {
      "minM2": 80,
      "maxM2": 90,
      "factor": 0.4
    }
  ],
  "modelosReferencia": [
    {
      "tipo": "2R planta baja",
      "m2Internos": 85.03,
      "jardinM2": 7.8,
      "roofM2": 0
    },
    {
      "tipo": "2R primer nivel",
      "m2Internos": 90.5,
      "jardinM2": 0,
      "roofM2": 0
    },
    {
      "tipo": "2R segundo nivel + roof",
      "m2Internos": 90.5,
      "jardinM2": 0,
      "roofM2": 36.68
    },
    {
      "tipo": "3R planta baja",
      "m2Internos": 98.14,
      "jardinM2": 9.13,
      "roofM2": 0
    },
    {
      "tipo": "3R primer nivel",
      "m2Internos": 105.22,
      "jardinM2": 0,
      "roofM2": 0
    },
    {
      "tipo": "3R segundo nivel + roof",
      "m2Internos": 105.22,
      "jardinM2": 0,
      "roofM2": 35.33
    }
  ],
  "incrementoNivel": [
    {
      "nivel": 1,
      "incrementoPct": 0.13
    },
    {
      "nivel": 2,
      "incrementoPct": 0
    },
    {
      "nivel": 3,
      "incrementoPct": 0.04
    }
  ],
  "areasInternasIncremento": [
    {
      "minM2": 89.068,
      "maxM2": 0.06,
      "factor": 0
    },
    {
      "minM2": 93.106,
      "maxM2": 0.04,
      "factor": 0
    },
    {
      "minM2": 97.14399999999999,
      "maxM2": 0.03,
      "factor": 0
    },
    {
      "minM2": 101.18199999999999,
      "maxM2": 0.02,
      "factor": 0
    }
  ],
  "areasInternasExtraPct": 4.037999999999999,
  "areasInternasExtraUmbralM2": 105.22,
  "sembradoSource": "1. Sembrado Misión La Agavia.xlsx"
} as const;

export type MisionLaGaviaEsquemaId = (typeof MISION_LA_GAVIA_SIMULADOR_CONFIG.esquemasPago)[number]["id"];
