import type { CorredorDesarrollo, CorredorZonaContexto } from "./types";

/** Catálogo comparativo del corredor sur — análisis de mercado zona Metropolitano / 413. */
export const CORREDOR_DESARROLLOS: CorredorDesarrollo[] = [
  {
    id: "el-condado",
    nombre: "El Condado",
    kmCorredor: 3,
    kmLabel: "km 3",
    desarrollador: "TAYCO",
    desarrolladorId: "tayco",
    municipio: "corregidora",
    carretera: "metropolitano",
    loteMinM2: 248,
    loteMaxM2: 333,
    precioMinM2: 7809,
    precioMaxM2: 9016,
    ticketDesde: 1_950_000,
    absorcionMes: 1.5,
    totalLotes: null,
    enganchePct: null,
    plazoMeses: null,
    amenidades: ["Pádel", "Fútbol", "Gym", "Alberca", "Casa club", "Ciclopista"],
    amenidadTags: ["padel", "gym-exterior", "alberca", "casa-club", "ciclovia"],
    ubicacion: {
      lat: 20.5080528,
      lng: -100.4041649,
      aproximada: false,
      mapsUrl: "https://maps.app.goo.gl/MwFTsEQh3SGsQT2H6",
    },
    mapQuery: "El Condado Corregidora Querétaro",
  },
  {
    id: "velasur",
    nombre: "Velasur",
    kmCorredor: 3.5,
    kmLabel: "km 3.5",
    desarrollador: "Grupo Velas",
    desarrolladorId: "grupo-velas",
    municipio: "corregidora",
    carretera: "metropolitano",
    loteMinM2: 227,
    loteMaxM2: 659,
    precioMinM2: 8500,
    precioMaxM2: 10_150,
    ticketDesde: 2_200_000,
    absorcionMes: 4.5,
    totalLotes: 900,
    enganchePct: null,
    plazoMeses: null,
    amenidades: ["Casa club", "Parque lineal 8,000 m²", "Dog park", "Pádel", "Alberca"],
    amenidadTags: ["casa-club", "pet-park", "padel", "alberca", "areas-verdes"],
    ubicacion: {
      lat: 20.5092836,
      lng: -100.4081006,
      aproximada: false,
      mapsUrl: "https://maps.app.goo.gl/FXmfD7EVEJT3fmdi8",
    },
    mapQuery: "Velasur Corregidora Querétaro",
  },
  {
    id: "real-del-bosque",
    nombre: "Real del Bosque",
    kmCorredor: 3.6,
    kmLabel: "km 3.6",
    desarrollador: "SUCOT",
    desarrolladorId: "sucot",
    municipio: "corregidora",
    carretera: "metropolitano",
    loteMinM2: 201,
    loteMaxM2: 312,
    precioMinM2: 6300,
    precioMaxM2: 7395,
    ticketDesde: 1_580_000,
    absorcionMes: 1.5,
    totalLotes: null,
    enganchePct: null,
    plazoMeses: null,
    amenidades: ["Lagos", "Senderismo", "Palapa", "Tenis", "Bosque 18,000 m²", "Parque 38,000 m²"],
    amenidadTags: ["lago", "senderos", "areas-verdes", "casa-club"],
    notas: "7 cotos",
    ubicacion: {
      lat: 20.508011,
      lng: -100.3999774,
      aproximada: false,
      mapsUrl: "https://maps.app.goo.gl/YMiZZ1y3cJtosb6h6",
    },
    mapQuery: "Real del Bosque Corregidora Querétaro",
  },
  {
    id: "simate",
    nombre: "Simaté",
    kmCorredor: null,
    kmLabel: "Noria · 600 m Metropolitano",
    desarrollador: "Grupo Investti",
    desarrolladorId: "investti",
    municipio: "corregidora",
    carretera: "noria",
    loteMinM2: 180,
    loteMaxM2: 400,
    precioMinM2: 6362,
    precioMaxM2: 7588,
    ticketDesde: 1_150_000,
    absorcionMes: 4.6,
    totalLotes: 312,
    enganchePct: null,
    plazoMeses: null,
    amenidades: [
      "15 ha · 23,000 m² áreas verdes exclusivas",
      "Vistas a 2,400 ha Parque Nacional El Cimatario",
      "Casa club (propiedad original del terreno)",
      "Alberca templada y área de alberca",
      "Canchas de pádel",
      "Área comercial exclusiva",
      "Parque infantil y áreas verdes de juego",
      "Parque para perros",
      "Zona de camping y área de picnic",
      "Andadores peatonales y ciclistas",
      "Co-working",
      "Mirador al Cimatario",
    ],
    amenidadTags: [
      "casa-club",
      "alberca",
      "padel",
      "area-comercial",
      "juegos-infantiles",
      "pet-park",
      "camping",
      "areas-verdes",
      "ciclovia",
      "coworking",
      "senderos",
    ],
    ubicacion: {
      lat: 20.5044375,
      lng: -100.3810625,
      aproximada: false,
      mapsUrl: "https://maps.app.goo.gl/7hc5EGwkd12VSgkg6",
    },
    brochureUrl: "/corredor/brochures/simate.pdf",
    mapQuery: "Simaté Parque Residencial, Camino a la Noria, Corregidora, Querétaro",
    convenioDirecto: true,
    notas:
      "Simaté Parque Residencial · pie del Cimatario. Camino a la Noria a 600 m del Blvd. Metropolitano. ~40% vendido (brochure feb 2026). 442 454 1730 · simate.mx. Precios de lista: validar con Investti.",
    guiaAsesor:
      "Portafolio Investti en acceso Noria: naturaleza premium (Cimatario) con amenidades club completas. Metraje brochure 180–400 m². Compite con Cañadas por familia Investti pero en otro acceso — posicionar tranquilidad y reserva natural vs volumen Metropolitano.",
    argumentosVenta: [
      "180–400 m² — rango oficial brochure feb 2026",
      "15 ha con 23,000 m² de áreas verdes exclusivas",
      "Pie del Parque Nacional El Cimatario — 2,400 ha de reserva",
      "Casa club histórica + alberca templada + pádel + coworking",
      "Cercanías: Tec Milenio, Fontanar, hospitales, Plaza Constituyentes",
      "40% vendido — proyecto en consolidación",
    ],
  },
  {
    id: "canadas-del-arroyo",
    nombre: "Cañadas del Arroyo",
    kmCorredor: 6.4,
    kmLabel: "km 6.4 · Metropolitano",
    desarrollador: "Grupo Investti",
    desarrolladorId: "investti",
    municipio: "corregidora",
    carretera: "metropolitano",
    loteMinM2: 160,
    loteMaxM2: 342,
    precioMinM2: 5327,
    precioMaxM2: 6146,
    ticketDesde: 940_000,
    absorcionMes: 7.8,
    totalLotes: 532,
    enganchePct: null,
    plazoMeses: null,
    amenidades: [
      "Cañadas del Arroyo Reserva",
      "Acceso controlado 24/7 · servicios ocultos",
      "Fibra óptica e internet en áreas comunes",
      "Más de 15 amenidades",
      "Alberca y casa club",
      "Cancha de pádel y canchas multiusos",
      "Parque lineal y senderos caminables",
      "Ciclopista y área de patinaje",
      "Gimnasio calistenia y gym al aire libre",
      "Parque infantil, arenero y área de juegos",
      "Parque para mascotas",
      "Área de asadores, terrazas y picnic",
      "Huerto y pabellón",
    ],
    amenidadTags: [
      "caseta-vigilancia",
      "alberca",
      "casa-club",
      "padel",
      "ciclovia",
      "pet-park",
      "juegos-infantiles",
      "gym-exterior",
      "huerto-urbano",
      "areas-verdes",
      "senderos",
    ],
    ubicacion: {
      lat: 20.4937675,
      lng: -100.3808319,
      aproximada: false,
      mapsUrl: "https://maps.app.goo.gl/ZQb8HiHUgmSoCC7A8",
    },
    brochureUrl: "/corredor/brochures/canadas-del-arroyo.pdf",
    mapQuery:
      "Cañadas del Arroyo Reserva, Blvd. Metropolitano km 6.4, Rancho Arroyo Hondo, Corregidora, Querétaro",
    convenioDirecto: true,
    notas:
      "Blvd. Metropolitano Santa Bárbara–Huimilpan km 6.4, Rancho Arroyo Hondo. Terrenos desde 160 m² (brochure feb 2026). Servicios a 6 km · 15 min ciudad. 442 454 1623 · canadasdelarroyo.com. Precios: validar lista vigente Investti.",
    guiaAsesor:
      "Producto Investti de volumen en Metropolitano (km 6.4): ticket de entrada del portafolio con 7.8 lotes/mes. Máx. ~342 m² — solapa con propuesta 220–260 m² de nueva etapa CDV. Destaca +15 amenidades y fibra óptica vs competencia km 8.",
    argumentosVenta: [
      "Desde 160 m² — brochure oficial feb 2026",
      "7.8 lotes/mes — 2.ª absorción del corredor sur",
      "532 lotes · zona de mayor plusvalía Corregidora",
      "Acceso controlado, servicios ocultos, fibra óptica",
      "15+ amenidades: pádel, alberca, huerto, parque lineal",
      "Servicios a 6 km: Fontanar, hospitales, Plaza Constituyentes",
    ],
  },
  {
    id: "canadas-del-valle",
    nombre: "Cañadas del Valle",
    kmCorredor: 8.5,
    kmLabel: "km 8.5 · Metropolitano",
    desarrollador: "Grupo Investti",
    desarrolladorId: "investti",
    municipio: "corregidora",
    carretera: "metropolitano",
    loteMinM2: 160,
    loteMaxM2: 547,
    precioMinM2: 4940,
    precioMaxM2: 6581,
    ticketDesde: 875_000,
    absorcionMes: 15,
    totalLotes: 2200,
    enganchePct: null,
    plazoMeses: null,
    amenidades: [
      "80+ ha · 150,000 m² áreas verdes · +1,500 árboles",
      "5 km andadores y ciclopistas",
      "El Patol — pie del Cimatario y reservas naturales",
      "Caseta 24/7 · 3 carriles entrada y salida",
      "Puente colgante y espejos de agua",
      "Parque lineal, bike park y ciclopista",
      "Tirolesa infantil y área de juegos",
      "Huerto urbano y parque para perros",
      "Canchas multiusos y pádel",
      "Restaurante y terraza de eventos",
      "Terrenos premium con vista a la cañada",
    ],
    amenidadTags: [
      "bike-park",
      "juegos-infantiles",
      "huerto-urbano",
      "pet-park",
      "padel",
      "tirolesa",
      "lago",
      "ciclovia",
      "senderos",
      "caseta-vigilancia",
      "areas-verdes",
      "casa-club",
    ],
    convenioDirecto: true,
    destacado: true,
    ubicacion: {
      lat: 20.4773005,
      lng: -100.3755297,
      aproximada: false,
      mapsUrl: "https://maps.app.goo.gl/LYyDBWzE2vatqZMr6",
    },
    brochureUrl: "/corredor/brochures/canadas-del-valle.pdf",
    mapQuery:
      "Cañadas del Valle, Blvd. Metropolitano km 8.5, El Patol, Corregidora, Querétaro",
    notas:
      "Brochure 2026: Etapa 1 en venta 160–250 m² + premium vista cañada. Proyecto +80 ha en El Patol. Rango histórico catálogo hasta 547 m² (otras etapas/polígonos). 15 lotes/mes. 442 456 5199 · canadasdelvalle.com. Blvd. Metropolitano km 8.5.",
    guiaAsesor:
      "Líder del corredor (15 lotes/mes). Brochure vigente: Etapa 1 en 160–250 m². Nueva etapa recomendada 220–260 m²: donde el sembrado vende más rápido (200–250 m² casi agotado), pipeline de apartados ~225 m² y ticket ~$1.09–$1.71M a lista CDV vigente.",
    argumentosVenta: [
      "Etapa 1: 160–250 m² (brochure feb 2026) + premium vista cañada",
      "Nueva etapa 220–260 m² — máximo mercado, ticket competitivo, sell-through probado",
      "15 lotes/mes — 3× absorción promedio del corredor sur",
      "80+ ha · 150,000 m² verdes · puente colgante y bike park",
      "2,200 lotes — mayor escala Investti en km 8.5 Metropolitano",
      "Ticket desde $875K · vecino de Preserve Country",
    ],
  },
  {
    id: "preserve-country",
    nombre: "Preserve Country",
    kmCorredor: 8.5,
    kmLabel: "km 8–9",
    desarrollador: "CR · Complejos Residenciales",
    desarrolladorId: "capital-realestate",
    municipio: "corregidora",
    carretera: "metropolitano",
    loteMinM2: 130,
    loteMaxM2: 250,
    precioMinM2: 5500,
    precioMaxM2: 6500,
    ticketDesde: 850_000,
    absorcionMes: 5,
    totalLotes: 900,
    enganchePct: null,
    plazoMeses: null,
    amenidades: [
      "Parque central (lago y fuentes danzarinas)",
      "Granja ecuestre",
      "Club deportivo",
      "Glamping",
      "Respiro Country (temazcal y zona zen)",
      "Huerto urbano",
      "Zona de cabañas",
      "Senderos German Silva",
      "Jardín aromático y sensorial",
      "Gran salón",
      "Coworking ecológico",
      "Cava",
      "Parque aventura (tirolesa, mirador, bike park)",
      "Centro de servicios y zona de restaurantes",
      "Casas y cabañas (producto vertical)",
    ],
    amenidadTags: [
      "lago",
      "hipico",
      "casa-club",
      "camping",
      "huerto-urbano",
      "senderos",
      "coworking",
      "tirolesa",
      "bike-park",
      "areas-verdes",
      "padel",
      "gym-exterior",
    ],
    ubicacion: {
      lat: 20.4828037,
      lng: -100.3768851,
      aproximada: false,
      mapsUrl: "https://maps.app.goo.gl/47QiAo6kfTuQrmhv6",
    },
    brochureUrl: "/corredor/brochures/preserve-country.pdf",
    mapQuery: "Preserve Country, Corregidora, Querétaro",
    notas:
      "Hábitat experiencial CR · Blvd. Metropolitano km 8–9. Privadas activas: El Molino y El Herrador (Blvd. Paseo Country). Servicios a ~5 min (Costco, escuelas, hospitales). Producto: terrenos + casas + cabañas. Brochure mar 2026.",
    guiaAsesor:
      "Competidor directo de Cañadas del Valle en km 8.5: metraje máximo ~250 m² — compite en el tramo bajo de la propuesta 220–260 m². Destaca amenidades premium (ecuestre, glamping, cava) y vertical (casas/cabañas). Precios de mercado pendientes de lista vigente.",
    argumentosVenta: [
      "Blvd. Metropolitano · Preserve Sur al norte · servicios a 5 min",
      "13 amenidades master-plan: lago central, granja ecuestre, parque aventura",
      "Urbanización sustentable — Ecología CR y Fundación CR",
      "Privadas El Molino y El Herrador en venta activa",
      "Oferta mixta: terrenos, casas town-house y cabañas",
    ],
  },
  {
    id: "preserve-sur",
    nombre: "Preserve Sur",
    kmCorredor: 11,
    kmLabel: "km 10–12 · Metropolitano",
    desarrollador: "CR · Complejos Residenciales",
    desarrolladorId: "capital-realestate",
    municipio: "corregidora",
    carretera: "metropolitano",
    loteMinM2: 153,
    loteMaxM2: 300,
    precioMinM2: 5128,
    precioMaxM2: 8100,
    ticketDesde: 806_400,
    absorcionMes: 9,
    totalLotes: 1200,
    enganchePct: null,
    plazoMeses: 36,
    amenidades: [
      "Master plan: sección ECUESTRE disponible",
      "Hípico y club ecuestre",
      "Casa club con alberca",
      "Tennis y canchas multiusos",
      "Roof bar y fogatero",
      "Lago y kayaks",
      "Dog park",
      "Gastronomía: Cuatro Corderos, Pizzas, Taquinos, La Barra de Roman Sur",
      "Áreas verdes y estadio Corregidores cercano",
    ],
    amenidadTags: [
      "hipico",
      "ecuestre",
      "lago",
      "kayak",
      "casa-club",
      "pet-park",
      "padel",
      "areas-verdes",
    ],
    ubicacion: {
      lat: 20.4918345,
      lng: -100.3779325,
      aproximada: false,
      mapsUrl: "https://maps.app.goo.gl/rrBjrxA7TDmjv5kB8",
    },
    brochureUrl: "/corredor/brochures/preserve-sur.pdf",
    mapQuery: "Preserve Sur, Blvd. Metropolitano, Cimatario, Corregidora, Querétaro",
    notas:
      "Capital Realestate / TERRENOS CR. Brochure 2026: desde $5,128/m² · inversión desde $806,400. Financiamiento 12, 24 y 36 meses. Única sección disponible: ECUESTRE (Arroyo, Sendero, Arboleda, Ciprés y Fresno vendidas).",
    guiaAsesor:
      "Competidor km 10–12 con fuerte componente ecuestre y gastronomía en club. Ticket entrada brochure $806K — por debajo de CDV en ticket pero metraje máx. 300 m². Solapa parcialmente con propuesta 220–260 m² de nueva etapa Valle.",
    argumentosVenta: [
      "Desde $5,128/m² · inversión desde $806,400 (brochure 2026)",
      "Sección Ecuestre — única disponible en master plan",
      "Hípico, lago, kayaks, casa club y roof bar",
      "9 lotes/mes absorción · 1,200 lotes totales",
      "Financiamiento 12, 24 y 36 meses",
      "Junto a Cimatario · servicios Costco, Fontanar, estadio",
    ],
  },
  {
    id: "faro-de-los-cisnes",
    nombre: "El Faro de los Cisnes",
    kmCorredor: 11.5,
    kmLabel: "km 11.5 · 413",
    desarrollador: "El Faro de los Cisnes",
    desarrolladorId: "el-faro-cisnes",
    municipio: "corregidora",
    carretera: "413",
    loteMinM2: 160,
    loteMaxM2: 280,
    precioMinM2: 5500,
    precioMaxM2: 8500,
    ticketDesde: 1_100_000,
    absorcionMes: null,
    totalLotes: null,
    enganchePct: null,
    plazoMeses: null,
    amenidades: [
      "5 lagos naturales",
      "Club hípico",
      "Club deportivo",
      "Servicios subterráneos",
      "Ciclovías",
      "Pádel y tenis",
      "Tirolesa y kayak",
      "Reserva El Batán",
    ],
    amenidadTags: [
      "lago",
      "hipico",
      "casa-club",
      "ciclovia",
      "padel",
      "tirolesa",
      "kayak",
      "areas-verdes",
      "caseta-vigilancia",
    ],
    ubicacion: {
      lat: 20.4490592,
      lng: -100.4297274,
      aproximada: false,
      mapsUrl: "https://maps.app.goo.gl/13RQGAGEq7WmP7DdA",
    },
    mapQuery: "El Faro de los Cisnes, Carretera 413 km 11.5, Corregidora, Querétaro",
    notas: "~135 ha · urbanismo autosustentable · Santa Bárbara–Coroneo.",
    guiaAsesor:
      "Vende naturaleza premium: lagos, hípico y reserva El Batán. Comparar ticket/m² vs Preserve y Cañadas en el simulador.",
    argumentosVenta: [
      "Carretera 413 km 11.5 — eje sur en consolidación",
      "Servicios subterráneos y baja densidad",
      "10–15 min a Constituyentes y El Pueblito",
      "Concepto autosustentable junto a reserva ecológica",
    ],
  },
  {
    id: "ciudad-maderas-corregidora",
    nombre: "Ciudad Maderas Corregidora",
    kmCorredor: 12.1,
    kmLabel: "km 12 · 413",
    desarrollador: "Ciudad Maderas",
    desarrolladorId: "ciudad-maderas",
    municipio: "corregidora",
    carretera: "413",
    loteMinM2: 108,
    loteMaxM2: 270,
    precioMinM2: 4500,
    precioMaxM2: 6500,
    ticketDesde: 450_000,
    absorcionMes: null,
    totalLotes: null,
    enganchePct: null,
    plazoMeses: null,
    amenidades: [
      "Casa club",
      "Alberca semiolímpica",
      "Gimnasio y vapor",
      "Tenis y multicanchas",
      "Pet park",
      "3 lagos artificiales",
      "Privadas con acceso controlado",
    ],
    amenidadTags: [
      "casa-club",
      "alberca",
      "gym-exterior",
      "padel",
      "pet-park",
      "lago",
      "caseta-vigilancia",
      "areas-verdes",
    ],
    ubicacion: {
      lat: 20.4413669,
      lng: -100.4365753,
      aproximada: false,
      mapsUrl: "https://maps.app.goo.gl/mZob8djhY4zWK51x6",
    },
    mapQuery: "Ciudad Maderas Corregidora, Carretera 413 km 12, Presa de Bravo, Querétaro",
    notas: "Privadas Palma, Peñón, Coníferas, etc. · zona Presa de Bravo / Coroneo.",
    guiaAsesor:
      "Ticket de entrada accesible vs competidores del corredor. Destaca enganche flexible y expansión por etapas del grupo Ciudad Maderas.",
    argumentosVenta: [
      "413 km 12 — mismo corredor que Faro y Valle Cardinal",
      "Marca Ciudad Maderas con múltiples privadas y amenidades club",
      "15 min El Pueblito · conexión Constituyentes",
      "Ideal prospecto que busca mensualidad baja y lote en crecimiento",
    ],
  },
  {
    id: "arroyo-del-pedregal",
    nombre: "Arroyo del Pedregal",
    kmCorredor: null,
    kmLabel: "Noria",
    desarrollador: "Arroyo del Pedregal",
    desarrolladorId: "arroyo-del-pedregal",
    municipio: "corregidora",
    carretera: "noria",
    loteMinM2: 72,
    loteMaxM2: 120,
    precioMinM2: 5500,
    precioMaxM2: 7000,
    ticketDesde: 450_000,
    absorcionMes: null,
    totalLotes: null,
    enganchePct: null,
    plazoMeses: null,
    amenidades: ["Casa club"],
    amenidadTags: ["casa-club"],
    notas: "Datos parciales en estudio comparativo.",
    ubicacion: {
      lat: 20.5033002,
      lng: -100.3830604,
      aproximada: false,
      mapsUrl: "https://maps.app.goo.gl/eMWnG4761sPnjLGj6",
    },
    mapQuery: "Arroyo del Pedregal Noria Querétaro",
  },
  {
    id: "valle-cardinal",
    nombre: "Valle Cardinal",
    kmCorredor: 18,
    kmLabel: "km 18",
    desarrollador: "Valle Cardinal",
    desarrolladorId: "valle-cardinal",
    municipio: "huimilpan",
    carretera: "413",
    loteMinM2: 150,
    loteMaxM2: 194,
    precioMinM2: 4891,
    precioMaxM2: 4891,
    ticketDesde: 735_000,
    absorcionMes: null,
    totalLotes: null,
    enganchePct: null,
    plazoMeses: null,
    amenidades: ["Lagos", "Pádel", "Usos múltiples", "Skate park", "Camping", "Viñedos", "Alberca", "Gimnasio"],
    amenidadTags: ["lago", "padel", "casa-club", "camping", "alberca", "gym-exterior"],
    ubicacion: {
      lat: 20.423159,
      lng: -100.2983034,
      aproximada: false,
      mapsUrl: "https://maps.app.goo.gl/h8Lgq3Dd736QjxPz9",
    },
    mapQuery: "Valle Cardinal Huimilpan Querétaro",
  },
];

export const CORREDOR_DESARROLLADORES = [
  { id: "investti", nombre: "Grupo Investti", proyectos: ["simate", "canadas-del-arroyo", "canadas-del-valle"] },
  {
    id: "capital-realestate",
    nombre: "CR · Complejos Residenciales",
    proyectos: ["preserve-country", "preserve-sur"],
  },
  { id: "ciudad-maderas", nombre: "Ciudad Maderas", proyectos: ["ciudad-maderas-corregidora"] },
  { id: "el-faro-cisnes", nombre: "El Faro de los Cisnes", proyectos: ["faro-de-los-cisnes"] },
  { id: "tayco", nombre: "TAYCO", proyectos: ["el-condado"] },
  { id: "grupo-velas", nombre: "Grupo Velas", proyectos: ["velasur"] },
  { id: "sucot", nombre: "SUCOT", proyectos: ["real-del-bosque"] },
  { id: "valle-cardinal", nombre: "Valle Cardinal", proyectos: ["valle-cardinal"] },
  { id: "arroyo-del-pedregal", nombre: "Arroyo del Pedregal", proyectos: ["arroyo-del-pedregal"] },
];

export const CORREDOR_ZONA: CorredorZonaContexto = {
  titulo: "Corredor sur — Metropolitano y 413",
  subtitulo:
    "Desarrollos de terreno en Corregidora, El Batán y Huimilpan sobre Blvd. Metropolitano (411), acceso Noria y carretera 413.",
  mapaEmbedUrl:
    "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d119420.5!2d-100.45!3d20.48!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x85d35a8b8b8b8b8b%3A0x0!2sBlvd.+Metropolitano%2C+Corregidora%2C+Qro.!5e0!3m2!1ses!2smx!4v1",
  mapaUrl: "https://maps.google.com/?q=Blvd+Metropolitano+Corregidora+Queretaro",
  mensajeAsesor:
    "Presenta Aliados del Corredor: convenio directo, precios vigentes y comparativo imparcial. Ubica en el mapa y afina con filtros.",
  puntosCercanos: [
    {
      id: "costco",
      nombre: "Costco Corregidora",
      categoria: "Comercial",
      tiempo: "2026",
      detalle: "Inversión ~$100 MDD · apertura nov 2026 · piso 8,000 m². Ancla de plusvalía en radio 3–5 km.",
      destacado: true,
    },
    {
      id: "libramiento",
      nombre: "Libramiento Sur-Poniente",
      categoria: "Conectividad",
      tiempo: "15 min",
      detalle: "Acceso al centro sur sin peaje vía libramiento.",
      destacado: true,
    },
    {
      id: "estadio",
      nombre: "Estadio Conspiradores",
      categoria: "Deporte / comercial",
      tiempo: "Zona sur",
      detalle: "Actividad deportiva y comercial creciente en el corredor.",
    },
    {
      id: "hospitales",
      nombre: "Hospitales y servicios",
      categoria: "Salud",
      tiempo: "20–30 min",
      detalle: "Red hospitalaria de Querétaro accesible vía libramiento y 57.",
    },
    {
      id: "plazas",
      nombre: "Plazas y retail",
      categoria: "Comercial",
      tiempo: "Corregidora",
      detalle: "Centros comerciales en crecimiento con la densificación del sur.",
    },
  ],
};

export function getCorredorDesarrolloById(id: string): CorredorDesarrollo | undefined {
  return CORREDOR_DESARROLLOS.find((d) => d.id === id);
}
