/** Tema claro para propuestas comerciales (presentación tipo PPT). */
export const propuestaSlide = {
  deck: "bg-white text-slate-800",
  header: "border-slate-200 bg-white text-slate-800",
  headerMuted: "text-slate-400",
  footer: "border-slate-200 bg-slate-50",
  footerText: "text-slate-600",
  footerMuted: "text-slate-400",
  slideBg: "bg-white",
  title: "font-[Georgia,'Times_New_Roman',serif] text-slate-900",
  body: "text-slate-600",
  bodyStrong: "text-slate-800",
  border: "border-slate-200",
  kpi: "border-slate-200 bg-slate-50",
  kpiAccent: "border-[#6cc24a]/35 bg-[#6cc24a]/8",
  kpiLabel: "text-slate-500",
  kpiValue: "text-slate-900",
  btnActive: "border-slate-300 bg-slate-100 font-semibold text-slate-900",
  btnIdle: "border-slate-200 text-slate-600 hover:border-slate-300",
  tableHead: "bg-slate-100 text-slate-500",
  tableRow: "border-slate-200",
  navBtn: "border-slate-200 bg-white/90 text-slate-700 shadow-sm hover:bg-slate-50",
  dotActive: "bg-[#6cc24a]",
  dotIdle: "bg-slate-300 hover:bg-slate-400",
  accent: "#6cc24a",
  heading: "#1e293b",
} as const;
